# Generated by Django 5.1.5 on 2025-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_customerdetail_order_shoes_delete_shoe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='colour',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GREEN', 'Green'), ('YELLOW', 'Yellow')], default='BLACK', max_length=20),
        ),
        migrations.AddField(
            model_name='shoes',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='category',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids')], max_length=20),
        ),
    ]
