# Generated by Django 5.1.5 on 2025-03-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shoes_shoe_image_alter_shoes_show_in_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='show_in_carousel',
        ),
    ]
