# Generated by Django 5.1.5 on 2025-03-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_shoes_show_in_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='show_in_carousel',
            field=models.BooleanField(null=True),
        ),
    ]
