# Generated by Django 4.2.7 on 2025-03-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shoes_show_in_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe_image/'),
        ),
    ]
