# Generated by Django 4.2.7 on 2025-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shoes_shoe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'shipped'), ('COMPLETED', 'completed'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
