# Generated by Django 4.2.7 on 2025-03-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='show_in_carousel',
        ),
    ]
